### ISSUE TITLE
potential multipart security issue?

### ISSUE THREAD

**Issue by laudiacay** [Nugine/s3s#51]
Unsure whether this is actually an issue- but- I don't think you do auth right on multipart uploads? I think anyone can upload and overwrite parts if they have the UUID for the upload_id?

**Comment by Nugine** [comment]
Thanks for the report! Confirmed security issue in `s3s-fs`.

**Comment by laudiacay** [comment]
oh cool
also hi, using your library in prod soon, you may see a medium amount of me in your github issues soon :)

**Comment by Nugine** [comment]
I'm glad to hear that you're planning to use `s3s` in production soon. This project needs feedback and contributors to keep evolving.

Note that `s3s-fs` is a sample implementation. It may cause security holes since it's not well-tested. 
`s3s` provides adapters rather than a complete server. Be careful if your server is facing attacks.

**Comment by laudiacay** [comment]
dw, we're not using s3sfs- just using it as inspiration
